//pins

#define SENSOR_SPEED_PIN 0
#define SENSOR_SPEED_INTERUPT 2
#define SENSOR_CADENCE_PIN 1
#define SENSOR_CADENCE_INTERUPT 3

#define BUTTON_LEFT_UP 8
#define BUTTON_LEFT_DOWN 9
#define BUTTON_RIGHT_UP 10
#define BUTTON_RIGHT_DOWN 11
#define BUTTON_SET 12
#define BUTTON_NORMAL_LATENCY 300
#define BUTTON_SHORT_LATENCY 100

#define DERAILLEUR_SERVO_FRONT 5
#define DERAILLEUR_SERVO_REAR 6
#define DERAILLEUR_TRIM_RATE 0.25
#define DERAILLEUR_TRIM_DELAY 1500

#define EEPROM_ADDR_INIT   0
#define EEPROM_ADDR_RESET   1
#define EEPROM_ADDR_GEARPOSITION_FRONT 2
#define EEPROM_ADDR_GEARPOSITION_REAR 3
#define EEPROM_ADDR_TRIM_SWITCH 4
#define EEPROM_ADDR_SYNC_SWITCH 5
#define EEPROM_ADDR_GEARPREF_START 10

#define LOOP_DELAY 100

#define SPEAKER_PIN 3
#define SPEAKER_FREQ 600
#define SPEAKER_FREQ_OFF 400
#define SPEAKER_DUR 20
//old







#define SPEED_REFRESH 500

#define SHIFT_CORRECTION_DELAY 2500
#define SHIFT_CORRECTION_RATE 0.2
#define SPEED_WHEELDETECTOR_CACHESIZE 40
#define SPEED_CRANCKSETDETECTOR_CACHESIZE 15
#define SPEED_WHEEL_TIMEOUT 5000
#define SPEED_CRANCKSET_TIMEOUT 3000
#define SPEED_KPH  0.06

#define SPEED_CRANCKSET_ANTISHAKE_TIMELATENCY 300
#define SPEED_WHEEL_ANTISHAKE_TIMELATENCY 50
#define ANTISHAKE_TIMELATENCY 150

#define EEPROM_SHIFTER_START 40 //need 60 address


#define EEPROM_TRANSMITTER_START 100

